name: '01-Example: Another action with choices'
on:
  workflow_dispatch:
    inputs:
      isNight:
        required: true
        type: choice
        options:
          - 'yes'
          - 'no'
        description: I will say good night if this value is set to "yes"
      name:
        default: 'Octocat'
        description: 'Name to greet'
        required: false
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodnight
        if: github.event.inputs.isNight == 'yes'
        run: echo "GREETING=Goodnight" >> $GITHUB_ENV
      - name: Say Hello
        if: github.event.inputs.isNight == 'no'
        run: echo "GREETING=Hello" >> $GITHUB_ENV
      - name: Generate output
        id: the-sentence
        run: echo "::set-output name=greeting-phrase::'${{ env.GREETING }} ${{ github.event.inputs.name }}'"

      - name: Actually say something
        run: echo "${{ steps.the-sentence.outputs.greeting-phrase }}"
